### ISSUE TITLE
Update alias HB_SHELL

### ISSUE THREAD

**Issue by S474N** [Paraphraser/IOTstackAliases#1]
After upgrade to newest version of Homebridge is necessary to change alias from:
`docker exec -it homebridge ash `

to: `docker exec -it homebridge bash`

More info about Homebridge changes:
https://github.com/oznu/docker-homebridge/releases

**Comment by Paraphraser** [comment]
Thanks for reporting this.

I have updated `dot_iotstack_aliases` so it does dynamic discovery. That means this type of "change of shell" problem should be easier to handle in the future.

The way it works is, the list of running containers is iterated (so your stack needs to be up when this happens). For each container, an attempt is made to see which of bash, ash, zsh or sh it knows about. The first result (usually bash) is taken and then the alias command is constructed dynamically.

Running `docker exec container which bash ash zsh sh` is fairly slow, particularly if you have a lot of containers and/or are running on a less powerful machine and/or running on SD rather than SSD, so the results are cached in `~/.cache/IOTstackAliases/cache`.

Thereafter, the cache is sourced on each login so it's as fast as it always was. The price, of course, is that if you add a new container you need to nuke the cache file so it can be rebuilt.

One side effect is that `INFLUX_SHELL` becomes `INFLUXDB_SHELL`. The same for the `HA_` and `HB_` prefixed aliases which are now `HOME_ASSISTANT_SHELL` and `HOMEBRIDGE_SHELL`. This improves consistency but may take a bit of getting used to.
